# Generated by Django 4.1.13 on 2024-05-09 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_useraplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraplication',
            old_name='firstname',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='useraplication',
            old_name='lastname',
            new_name='notice_period',
        ),
        migrations.AddField(
            model_name='useraplication',
            name='current_company',
            field=models.CharField(default=django.utils.timezone.now, max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraplication',
            name='current_location',
            field=models.CharField(default=django.utils.timezone.now, max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraplication',
            name='fullname',
            field=models.CharField(default=django.utils.timezone.now, max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraplication',
            name='github_profile',
            field=models.URLField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraplication',
            name='linkedin_profile',
            field=models.URLField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraplication',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraplication',
            name='portfolio',
            field=models.URLField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraplication',
            name='referral_source',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraplication',
            name='salary_expectation',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraplication',
            name='years_of_experience',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraplication',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
