# Generated by Django 4.1.13 on 2024-08-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_firstname_useraplication_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraplication',
            name='contact_me',
            field=models.BooleanField(default=False),
        ),
    ]
