# Generated by Django 4.2.7 on 2024-08-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_useraplication_contact_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='engagement_model',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
