# Generated by Django 4.2.1 on 2024-08-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contact_engagement_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraplication',
            name='salary_expectation',
            field=models.CharField(max_length=105),
        ),
    ]
