# Generated by Django 4.2.1 on 2024-08-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_alter_useraplication_salary_expectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraplication',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
